Controllers/QuoteAdminController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using System.Collections.Generic;
using QuoteGeneratorAPI.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace QuoteGeneratorAPI.Controllers {

    public class QuoteAdminController : Controller {    
        private IWebHostEnvironment environment;
        // setup the environment
        public QuoteAdminController(IWebHostEnvironment env) {
            environment = env;
        }
        // initilization of the web app - first hit
        public IActionResult Index() {
            QuoteGeneratorAdmin quoteGeneratorAdmin = new QuoteGeneratorAdmin();
            quoteGeneratorAdmin.setupMe();
            return View(quoteGeneratorAdmin);
        }

        // use this method when submitting a quote
        [HttpPost]
        public IActionResult AddQuote(QuoteGeneratorAdmin quoteGeneratorAdmin, IFormFile selectedFile, string author, string quote, string permalink) {
            quoteGeneratorAdmin.setupMe();
            Quote quoteCreate = new Quote();
            ImageUploader imageUploader = new ImageUploader(environment, "uploads");
            string date = DateTimeOffset.Now.ToUnixTimeSeconds().ToString();
            Console.WriteLine(DateTimeOffset.Now.ToUnixTimeSeconds());
            int result = imageUploader.uploadImage(selectedFile, date);
            Console.WriteLine("Upload result: " + result);
            if (result == 5) {
                TempData["feedback"] = "Quote Succesfully added";
                quoteCreate.author = author;
                quoteCreate.quote = quote;
                quoteCreate.permalink = permalink;
                quoteCreate.image = "img_"+ date +"."+selectedFile.FileName.Split('.')[1];
                quoteCreate.create();
                return RedirectToAction("Index");
            } 

            if(!ModelState.IsValid) {
                if (result == 0){
                TempData["feedback"] = "Image upload failed -- No File Selected";
                }
                else if (result == 1){
                    TempData["feedback"] = "Image upload failed -- Incorrect File Type";
                }
                else if (result == 2){
                    TempData["feedback"] = "Image upload failed -- File is too big";
                }
                else if (result == 3){
                    TempData["feedback"] = "Image upload failed -- File name is too long";
                }
                else if (result == 4){
                    TempData["feedback"] = "Image upload failed -- Error uploading image";
                }
                return View("Index", quoteGeneratorAdmin);
            }

            return View("Index", quoteGeneratorAdmin);
        }
        
        // use this action method to delete a quote
        [HttpPost]
        public IActionResult DeleteQuote(QuoteGeneratorAdmin quoteGeneratorAdmin, string filename) {
            Quote quote = new Quote();
            quote.id = quoteGeneratorAdmin.QuoteID;
            string file = quote.readImageName(quoteGeneratorAdmin.QuoteID);
            bool success = quote.Delete();
            quoteGeneratorAdmin.deleteImage(environment, "uploads/"+file);
            TempData["deleted"] = "Quote Succesfully deleted";
            return RedirectToAction("Index");
        }

        // use this method to generate the random quote from the database
        [Route("quotes/{quoteNum}")]
        public JsonResult RandomQuotes(QuoteGeneratorAdmin quoteGeneratorAdmin, int quoteNum){
            quoteGeneratorAdmin.setupMeJson();
            return Json(quoteGeneratorAdmin.getRandomQuotes(quoteNum));
        }

    }
}

Views/QuoteAdmin/Index.cshtml
@model QuoteGeneratorAdmin

<div>
    <h1 class="text-info">QuoteGenerator Admin V1.0</h1>
    <h5 class="text-info">Project II : INET2005 Web Appplication Programming I</h5>

    <h3 id="addHeader" class="text-info">Add quote to quote generator</h3>

    <form enctype="multipart/form-data" asp-controller="QuoteAdmin" asp-action="AddQuote">
        <div class="form-row">
            <div class="col-md-6">
                <label>Author:</label>
                <input type="text" class="form-control" asp-for="@Model.author" name="author" value="@Model.author" maxlength="100" placeholder="Author"/>
                <span asp-validation-for="@Model.author" class="text-danger"></span>
            </div>
        </div>
        <div class="form-row">
            <div class="col-md-6">
                <label>Quote:</label>
                <textarea type="text" class="form-control" asp-for="@Model.quote" name="quote" maxlength="100" placeholder="Insert Quote here"></textarea>
                <span asp-validation-for="@Model.quote" class="text-danger"></span>
            </div>
        </div>
        <div class="form-row">
            <div class="col-md-6">
                <label>Link:</label>
                <input type="text" class="form-control" asp-for="@Model.permalink" name="permalink" value="@Model.permalink" maxlength="100" placeholder="Link to Quote"/>
                <span asp-validation-for="@Model.permalink" class="text-danger"></span>
            </div>
        </div>
        <div class="form-row" style="padding-top: 8px; padding-left: 5px;">
            <label class="btn btn-info">
                Browse for Quote Image<input id="btnUpload" type="file" asp-for="@Model.image" name="selectedFile" hidden onchange="getFileData(this);"/>
            </label>
            <span id="fileNameToUpload"></span>
        </div>
        
        <div class="form-row" style="padding-left: 5px;">
            <button type="submit" class="btn btn-info" name="submit">Submit</button>
            <span id="feedbackData" class="text-danger">@TempData["feedback"]</span>
            <span class="text-success">@TempData["success"]</span>
        </div>
    </form>

    <h3 id="deleteHeader" class="text-info">Delete Quote from Quote Generator</h3>
    <form asp-controller="QuoteAdmin" asp-action="DeleteQuote">
        <div id="quotesContainer">
            <select id="lstQuotes" class="btn btn-info" asp-for="@Model.QuoteID" asp-items="@Model.QuotesList" style="max-width: 550px !important;"></select>
        </div>
        <div id="btnDelete" class="form-row">
            <button type="submit" class="btn btn-info">Delete</button>
            <span id="deletedData" class="text-danger">@TempData["deleted"]</span>
        </div>
    </form>

</div>